
INSERT INTO GENRE_NAME(GENRE_NAME)
values(     'Комедия');
INSERT INTO GENRE_NAME(GENRE_NAME)
values('Драма');
INSERT INTO GENRE_NAME(GENRE_NAME)
values('Мультфильм');
INSERT INTO GENRE_NAME(GENRE_NAME)
values('Триллер');
INSERT INTO GENRE_NAME(GENRE_NAME)
values('Боевик');
INSERT INTO GENRE_NAME(GENRE_NAME)
values('Документальный');

INSERT INTO FILMS_RATING(RATING_NAME)
values('G');
INSERT INTO FILMS_RATING(RATING_NAME)
values('PG');
INSERT INTO FILMS_RATING(RATING_NAME)
values('PG-13');
INSERT INTO FILMS_RATING(RATING_NAME)
values('R');
INSERT INTO FILMS_RATING(RATING_NAME)
values('NC-17');